/* =========================================================
   영어 번역 사전 (12단계)

   - 왼쪽 "번호표"는 index.html / mypage.html 의 data-i18n="..." 과 똑같아야 합니다.
   - 오른쪽 글만 고치면 영어 화면이 바뀝니다. HTML 은 건드리지 않아도 됩니다.
   - <br> 줄바꿈 / <strong>·<b> 굵은 글씨 / <small> 작은 설명글 / <em> 강조색
     → 이 표시는 그대로 두고 그 사이의 글자만 바꿔 주세요.
   - 금액은 원화(KRW) 그대로 적었습니다. 환율이 바뀌면 곤란해서 달러로 바꾸지 않았습니다.
   ========================================================= */
window.INFINITY_TEXT = window.INFINITY_TEXT || {};
window.INFINITY_TEXT.en = {

  /* ===== 브라우저 탭 제목 · 검색 결과 설명 ===== */
  'meta.title': 'INFINITY Program | Become International Cruise Ship Crew',
  'meta.desc' : 'Graduated, but the job market feels closed? One year from now your workplace could be a 6-star hotel on the Caribbean. Request a free INFINITY Program consultation.',

  /* ===== 상단 바 ===== */
  'header.logoAlt': 'INFINITY Program logo',
  'header.cta'    : 'Free consult',

  /* ===== 1. 첫 화면 ===== */
  'hero.bgAlt' : 'A cruise ship at sea',
  'hero.trust' : '🏛️ Malaysian government-recognised school · 1,000+ graduates',
  'hero.kicker': 'Graduated — and every door still closed?',
  'hero.h1'    : 'In one year, your workplace could be a<br><em><span class="nowrap">6-star hotel</span> <span class="nowrap">on the Caribbean</span></em>',
  'hero.sub'   : 'A USD salary while you travel the world.<br>Meals and lodging free — <strong>save all of it</strong>.',
  'hero.b1': 'Salary paid<br>in US dollars',
  'hero.b2': 'No income tax on salary<small>Under high-seas employment rules</small>',
  'hero.b3': 'Free meals<br>and lodging',
  'hero.b4': 'See the world<br>while you earn',
  'hero.btnApply'    : '📝 Request a free consultation',
  'hero.btnChat'     : '💬 Chat 1:1 on WhatsApp',
  'hero.btnChat.href': 'https://wa.me/qr/HMQUC5RYMIVKO1',

  /* ===== 2. 현실 비교 ===== */
  'cmp.h2'  : 'The same year —<br>where will you spend it?',
  'cmp.lead': 'What you choose today decides where you stand a year from now.',
  'cmp.them': 'Job hunting at home',
  'cmp.us'  : 'Cruise ship crew',
  'cmp.r1' : '📅 One year from now',
  'cmp.r1a': '<span class="sr-only">Job hunting at home: </span>Still padding your resume and filing applications',
  'cmp.r1b': '<span class="sr-only">Cruise ship crew: </span>Working aboard a 6-star-hotel-class cruise ship',
  'cmp.r2' : '💵 Salary',
  'cmp.r2a': '<span class="sr-only">Job hunting at home: </span>Local currency, taxed at source',
  'cmp.r2b': '<span class="sr-only">Cruise ship crew: </span>US dollars, no income tax on salary',
  'cmp.r3' : '🏠 Living costs',
  'cmp.r3a': '<span class="sr-only">Job hunting at home: </span>Rent, food and transport come out of your pocket',
  'cmp.r3b': '<span class="sr-only">Cruise ship crew: </span>Meals and lodging provided free',
  'cmp.r4' : '🐷 Savings',
  'cmp.r4a': '<span class="sr-only">Job hunting at home: </span>Little left once living costs are paid',
  'cmp.r4b': '<span class="sr-only">Cruise ship crew: </span>Most of your salary can go straight to savings',
  'cmp.r5' : '✈️ Experience',
  'cmp.r5a': '<span class="sr-only">Job hunting at home: </span>Domestic work history only',
  'cmp.r5b': '<span class="sr-only">Cruise ship crew: </span>World travel + overseas experience (a strong edge for hotel and airline jobs)',
  'cmp.punch': 'The same year — but a very different <b>bank balance and resume</b>.',
  'cmp.cta'  : 'Could I do this? Get a free consultation',

  /* ===== 3. 무료 상담 신청서 ===== */
  'form.h2'  : 'Request a free consultation and admission pack',
  'form.lead': 'Leave your details and an advisor will contact you directly.',
  'form.name'       : 'Full name',
  'form.name.ph'    : 'e.g. John Smith',
  'form.phone'      : 'Phone number',
  'form.phone.ph'   : '+60 11-1234-5678',
  'form.phone.hint' : 'Please start with your country code, for example +60 or +82',
  'form.email'      : 'Email',
  'form.eng'        : 'Current spoken English level (optional)',
  'form.choose'     : 'Please choose',
  'form.eng1'       : 'Basic (greetings only)',
  'form.eng2'       : 'Elementary (simple conversation)',
  'form.eng3'       : 'Intermediate (everyday conversation)',
  'form.eng4'       : 'Advanced (work conversation)',
  'form.langs'      : 'Other languages you speak (optional)',
  'form.langs.ph'   : 'e.g. Mandarin – intermediate. Write "none" if none.',
  'form.prog'       : 'Programme you are interested in (optional)',
  'form.choose2'    : 'Please choose',
  'form.prog.a'     : 'Cruise interview',
  'form.prog.b'     : 'Internship (6 months) + cruise interview',
  'form.prog.c'     : 'English course (12 weeks) + cruise interview',
  'form.prog.d'     : 'English course (12 weeks) + internship (6 months) + cruise interview',
  'form.prog.e'     : 'Birmingham Diploma (12 months)',
  'form.prog.x'     : 'Not sure yet',
  'form.agree'      : 'I agree to the collection and use of my personal data',
  'form.agree.more' : 'See details',
  'form.pp1'        : 'Data collected: name, phone number, email, English level, other languages, programme of interest',
  'form.pp2'        : 'Purpose: career consultation and sending admission information',
  'form.pp3'        : 'Retention: 1 year after the consultation ends (deleted immediately on request)',
  'form.pp4'        : 'You may decline, but we will not be able to process your consultation request.',
  'form.submit'     : 'Request a free consultation and admission pack',
  'form.foot'       : '※ Your details are used only for career consultation, nothing else.',

  /* ===== 4. 국제 크루즈란? ===== */
  'cr.h2'  : 'Cruise ship crew: the benefits are different',
  'cr.img1': 'A cruise ship sailing the open sea',
  'cr.p1': '<strong>Counted as 6-star hotel experience</strong> — a strong edge for hotel and airline jobs later',
  'cr.p2': '<strong>Paid in US dollars</strong> — no tax on salary (high-seas employment rules)',
  'cr.p3': '<strong>Fast promotion and pay rises</strong>',
  'cr.p4': '<strong>Everything you need on board</strong> — cabin, meals and daily life all provided',
  'cr.stats': 'INFINITY in numbers',
  'cr.s1': '<b>1,000+</b>graduates',
  'cr.s2': '<b>35+</b>official cruise line partners',
  'cr.s3': '<b>KL</b>cruise training centre in Kuala Lumpur, Malaysia',
  'cr.s4': 'Partner regions: USA, Alaska, Norway, the Mediterranean, Southeast Asia',
  'cr.gov': '<b>Officially recognised by the Malaysian government</b>We issue student visas ourselves · ordinary language schools cannot',
  'cr.img2': 'Official cruise line partners',
  'cr.img2.cap': '35+ cruise lines hiring',
  'cr.job'      : 'What will you actually do?',
  'cr.job.lead' : 'Based on your English and interview, you are placed in one of <strong>76 roles across 16 departments</strong>. (Pay varies by role.)',
  'cr.d1': 'Cabin care',
  'cr.d2': 'Ship galley',
  'cr.d3': 'Hotel',
  'cr.d4': 'Beverage service',
  'cr.d5': 'Food & beverage',
  'cr.d6': 'Deck',
  'cr.d7': 'Cooking',
  'cr.d8': 'Engine',
  'cr.d9': 'Restaurant',
  'cr.d10': 'Casino',
  'cr.d11': 'Instructor',
  'cr.d12': 'Management',
  'cr.d13': 'Recruiting',
  'cr.d14': 'Room service',
  'cr.d15': 'Technical',
  'cr.d16': 'Other',
  'cr.d.note': 'The number beside each department is how many roles it has.',
  'cr.d.more': 'Example: see the 12 roles in HOUSEKEEPING',
  'cr.img3': 'Cruise ship size comparison',
  'cr.req' : 'Entry requirements',
  'cr.req1': 'Aged 21 to under 35',
  'cr.req2': 'High school graduate or above',
  'cr.req3': 'Able to hold a conversation in English',
  'cr.req4': '1+ year in a 5-star hotel or tourism role',
  'cr.req.note': 'Do not worry if you fall short. If your English needs work we have the <strong>English course</strong>; if you lack experience we have the <strong>5-star hotel internship</strong>.',

  /* ===== 5. 나에게 맞는 프로그램 찾기 ===== */
  'fd.h2'   : 'Find the right programme for you',
  'fd.lead' : 'Answer two questions and we will recommend a programme.',
  'fd.q1'   : 'Q1. Can you hold an everyday conversation in English?',
  'fd.yes1' : 'Yes',
  'fd.no1'  : 'No',
  'fd.q2'   : 'Q2. Do you have 1+ year of hotel or tourism experience?',
  'fd.yes2' : 'Yes',
  'fd.no2'  : 'No',
  'fd.empty': 'Answer both questions to see your recommendation.',

  /* ===== 6. 프로그램 A~D ===== */
  'fx.note': '※ US dollar amounts are converted at the rate of 20 September 2026 (US$1 = KRW 1,387) and change with the exchange rate. The Korean won figure is the actual price.',
  'pg.h2': 'Programmes',
  'pg.a.t'  : 'A. Cruise interview',
  'pg.a.who': 'For those who <strong>already have both</strong> English and hotel experience',
  'pg.b.t'  : 'B. Internship (6 months) + cruise interview',
  'pg.b.who': 'For those with English but <strong>no hotel experience</strong>',
  'pg.c.t'  : 'C. English course (12 weeks) + cruise interview',
  'pg.c.who': 'For those with hotel experience but <strong>weaker English</strong>',
  'pg.d.t'  : 'D. English course (12 weeks) + internship (6 months) + cruise interview',
  'pg.d.who': 'For those who need <strong>both</strong> English and experience',
  'pg.i.visa'  : 'Tourist visa',
  'pg.i.intv'  : 'Cruise interviews (1st / 2nd / final)',
  'pg.i.intv2' : 'Cruise interviews (1st / 2nd / final)',
  'pg.i.pick'  : 'Airport pickup',
  'pg.i.svisa' : '1-year student visa (local medical check included) <a href="#gov-certified" class="gov-tag">government-certified</a>',
  'pg.i.intern': '5-star hotel internship placement (6 months)',
  'pg.i.eng'   : 'INFINITY 12-week English course (registration and level test included)',
  'pg.v.0'   : 'Free',
  'pg.v.10'  : 'KRW 100,000<em class="fx">≈ US$72</em>',
  'pg.v.75'  : 'KRW 750,000<em class="fx">≈ US$541</em>',
  'pg.v.100' : 'KRW 1,000,000<em class="fx">≈ US$721</em>',
  'pg.v.135' : 'KRW 1,350,000<em class="fx">≈ US$973</em>',
  'pg.v.300' : 'KRW 3,000,000<em class="fx">≈ US$2,163</em>',
  'pg.v.440' : 'KRW 4,400,000<em class="fx">≈ US$3,172</em>',
  'pg.total' : 'Total', 'pg.v.100b': 'KRW 1,000,000<em class="fx">≈ US$721</em>',
  'pg.total2': 'Total', 'pg.v.520' : 'KRW 5,200,000<em class="fx">≈ US$3,749</em>',
  'pg.total3': 'Total', 'pg.v.525' : 'KRW 5,250,000<em class="fx">≈ US$3,785</em>',
  'pg.total4': 'Total', 'pg.v.960' : 'KRW 9,600,000<em class="fx">≈ US$6,921</em>',
  'pg.total5': 'Total',
  'pg.ex' : 'Not included in any programme',
  'pg.ex1': 'Flights, accommodation, local transport, personal spending money',
  'pg.ex2': 'Boarding preparation agency fee after you pass (approx. KRW 720,000 / US$519, varies by cruise line)',
  'pg.ex3': 'Visa and paperwork costs once back home before boarding (approx. KRW 600,000 / US$433)',
  'pg.ex4': 'For accommodation, see <a href="#housing">Accommodation</a> below.',

  /* ===== 7. 버밍엄 Diploma ===== */
  'bcu.badge': 'SPECIAL · UK university Diploma',
  'bcu.logo' : 'Birmingham City University logo',
  'bcu.h2'   : 'E. Birmingham City University Diploma, UK (12 months)',
  'bcu.lead' : 'A Diploma that takes 2 years 6 months in the UK is completed at INFINITY in Malaysia in <strong>12 months including the internship</strong>. Graduation leads straight through to the final cruise interview.',
  'bcu.p1': 'You receive a Birmingham City University Diploma certificate',
  'bcu.p2': 'Credits are recognised if you go on to another university',
  'bcu.p3': 'Graduates can be verified on the university’s official website',
  'bcu.img1': 'Photo of an actual Diploma certificate',
  'bcu.img2': 'Graduate verification page on the university website',
  'ui.swipe': 'Swipe to see more →',
  'bcu.major': 'Three majors',
  'bcu.m1': 'Diploma in Hospitality Operations',
  'bcu.m2': 'Diploma in Food Preparation & Culinary Arts',
  'bcu.m3': 'Diploma in Food & Beverage Service Operations',
  'bcu.img3' : 'Subjects in each major',
  'bcu.intake': 'Intakes: <strong>January, April, July and October every year</strong>',
  'bcu.req' : 'Entry requirements',
  'bcu.req1': 'Aged 19 to under 35',
  'bcu.req2': 'High school graduate or above',
  'bcu.req3': 'Basic conversational English',
  'bcu.req4': 'No restrictions on travelling abroad',
  'bcu.tl' : 'How it runs (example: applying in April)',
  'bcu.tl1': '<strong>April 2026</strong> — consultation and application',
  'bcu.tl2': '<strong>May 2026</strong> — student visa (about 4 weeks), arrival in Malaysia, English course begins (6 months)',
  'bcu.tl3': '<strong>November 2026</strong> — 5-star hotel internship begins (6 months); Diploma awarded on completion',
  'bcu.tl4': '<strong>May 2027</strong> — cruise interviews',
  'bcu.tl5': '<strong>June 2027</strong> — return home, STCW training and paperwork, waiting for US visa approval (up to 4 weeks)',
  'bcu.tl6': '<strong>July 2027</strong> — travel to your cruise line’s departure port and start work',
  'bcu.img4': 'Arriving at the airport in Malaysia',
  'bcu.img5': 'Orientation',
  'bcu.img6': 'Students on the Birmingham programme',
  'bcu.price': 'Price',
  'bcu.pr1': '<a href="#gov-certified" class="gov-tag">Government-certified</a> visa and admission handling (airport pickup, 1-year student visa, local medical check, visa stamp duty, paperwork management)',
  'bcu.pr2': 'Diploma course (24 weeks) + 5-star hotel internship (6 months)',
  'bcu.pr3': 'Cruise interviews (1st / 2nd / final)',
  'bcu.v'  : 'KRW 13,700,000<em class="fx">≈ US$9,877</em>',
  'bcu.pr.note': 'What is not included is the same as programmes A–D.',
  'bcu.vs'   : 'A 2-year local college vs the Birmingham programme',
  'bcu.vs.h1': '', 'bcu.vs.h2': '2-year college at home', 'bcu.vs.h3': 'Birmingham programme',
  'bcu.vs.a1': 'Length',    'bcu.vs.a2': '2 years', 'bcu.vs.a3': '12 months (internship included)',
  'bcu.vs.b1': 'Tuition',   'bcu.vs.b2': 'Over KRW 20,000,000<em class="fx">≈ US$14,420 · about KRW 5,000,000 (US$3,605) per semester</em>', 'bcu.vs.b3': 'KRW 13,700,000<em class="fx">≈ US$9,877</em>',
  'bcu.vs.c1': 'Award',     'bcu.vs.c2': 'Local associate degree', 'bcu.vs.c3': 'Birmingham City University Diploma',
  'bcu.vs.d1': 'Job link',  'bcu.vs.d2': 'None', 'bcu.vs.d3': '1st, 2nd and final cruise interviews included',

  /* ===== 8. 교육센터 ===== */
  'ct.h2'  : 'INFINITY Training Center',
  'ct.lead': 'A training centre officially certified by Malaysia’s Ministry of Education (M.O.E), in central Kuala Lumpur. We are an official IELTS partner and a cruise crew agency.',
  'ct.gov.h': 'Officially recognised<br>by the Malaysian government',
  'ct.gov.p': '<b>Not just any school can issue a student visa.</b><br>Only institutions recognised by the Malaysian government can.',
  'ct.gov.no'  : 'Ordinary language school',
  'ct.gov.no1' : 'No official government certification',
  'ct.gov.no2' : '<b>Cannot issue a student visa at all</b>',
  'ct.gov.yes' : 'INFINITY Training Center',
  'ct.gov.yes1': 'Officially certified by Malaysia’s Ministry of Education (M.O.E)',
  'ct.gov.yes2': '<b>Can issue student visas directly</b>',
  'ct.gov.foot': 'That is why at INFINITY a <b>1-year student visa</b> carries you safely through the English course and into the 5-star hotel internship.',
  'ct.t1': 'Teachers with international school experience',
  'ct.t2': 'English courses by level, beginner to advanced (adult classes included)',
  'ct.t3': '1:1 lessons and small classes of 3–5 students',
  'ct.img1': 'Training centre entrance',
  'ct.img2': 'A class in progress',
  'ct.img3': 'A class in progress',
  'ct.img4': 'Students at the training centre',
  'ct.fac': 'Facilities',
  'ct.f1': '11 one-to-one classrooms',
  'ct.f2': '8 classrooms for 8 students',
  'ct.f3': '1 classroom for 25 students',
  'ct.f4': '1 presentation room for 50',
  'ct.f5': 'Student lounge',
  'ct.img5': 'One-to-one classroom',
  'ct.img6': 'Presentation room',
  'ct.img7': 'Student lounge',
  'ct.img8': 'Map showing the training centre',
  'ct.img8.cap': '5 min walk',
  'ct.in' : 'Paid 5-star hotel internship (6 months)',
  'ct.in1': 'Placed to match your experience and preferred field after meeting a local manager',
  'ct.in2': 'Monthly pay around RM1,200',
  'ct.in3': 'A 5-star hotel work certificate on completion (submitted with your cruise application; counts as 1 year of experience)',
  'ct.img9' : 'Internship hotel',
  'ct.img10': 'Internship hotel',
  'ct.img11': 'Working at the internship hotel',

  /* ===== 9. 합격 과정 ===== */
  'pc.h2': 'The path to getting hired',
  'pc.s1' : '<strong>Video consultation</strong> — talk to an INFINITY cruise advisor before you enrol (if you lack experience, the 6-month hotel internship raises your chances)',
  'pc.s2' : 'Cruise interviews',
  'pc.s2b': ' — held during your course',
  'pc.s2c': 'Personality assessment (on computer, differs by cruise line)',
  'pc.s2d': 'English test (on computer, same for every cruise line, valid for 1 year once passed)',
  'pc.s2e': 'Final interview (in English)',
  'pc.s3' : '<strong>You pass</strong> — you receive both the US crew work visa (C1/D) and the 10-year US travel visa (B1/B2)',
  'pc.s4' : '<strong>If you do not pass</strong> — we prepare you for the next interview round',
  'pc.img1': 'Video interview',
  'pc.img2': 'Final interview',
  'pc.img3': 'Letter of acceptance',
  'pc.img4': 'Cruise ship crew',
  'pc.prep': 'What to prepare at home after you pass',
  'pc.th1': 'Item', 'pc.th2': 'Details', 'pc.th3': 'Time', 'pc.th4': 'Cost',
  'pc.t1a': 'Medical check', 'pc.t1b': 'Examination at an approved hospital (blood, chest X-ray, etc.)', 'pc.t1c': 'About 1 month', 'pc.t1d': 'Approx. KRW 200,000–350,000<em class="fx">≈ US$144–252</em>',
  'pc.t2a': 'Paperwork', 'pc.t2b': 'Criminal record check (police), seafarer’s book (regional maritime office)', 'pc.t2c': '1 day', 'pc.t2d': 'Approx. KRW 10,000<em class="fx">≈ US$7</em>',
  'pc.t3a': 'US visa', 'pc.t3b': 'Apply for C1/D and B1/B2 with your acceptance letter', 'pc.t3c': 'About 10 days', 'pc.t3d': 'Approx. KRW 200,000<em class="fx">≈ US$144</em>',
  'pc.t4b': 'Maritime safety training (Carnival Cruise trains you on board instead)', 'pc.t4c': 'About 6 weeks', 'pc.t4d': 'Approx. KRW 180,000<em class="fx">≈ US$130</em>',
  'pc.note': '※ Required documents can differ by cruise line; we will guide you precisely once you pass.',

  /* ===== 10. 숙소 ===== */
  'hs.h2'  : 'Accommodation',
  'hs.note': '※ The places below are <strong>examples</strong>. Depending on availability you may be placed in a comparable residence.',
  'hs.a' : 'Type A: Vipod Residences',
  'hs.a1': 'Large room RM2,500 / month',
  'hs.a2': 'Small room RM2,000 / month',
  'hs.a3': '5 minutes on foot to the training centre',
  'hs.a4': 'WiFi included, electricity billed separately',
  'hs.ia1': 'Type A bedroom', 'hs.ia2': 'Type A living room', 'hs.ia3': 'Type A kitchen', 'hs.ia4': 'Type A swimming pool',
  'hs.b' : 'Type B: One-Stop Residences (two room types)',
  'hs.b1': 'Twin share RM1,000 / person',
  'hs.b2': 'Single room RM2,000 / person',
  'hs.b3': 'Two metro stops from the training centre',
  'hs.b4': 'WiFi included, electricity billed separately, gym available',
  'hs.ib1': 'Type B bedroom', 'hs.ib2': 'Type B living room', 'hs.ib3': 'Type B kitchen', 'hs.ib4': 'Type B swimming pool', 'hs.ib5': 'Type B gym',

  /* ===== 11. 연락처 ===== */
  'ctc.h2'  : 'Get in touch any time',
  'ctc.tel' : 'Phone',
  'ctc.kr'  : '🇰🇷 Korea',
  'ctc.my'  : '🇲🇾 Malaysia',
  'ctc.mail': 'Email',
  'ctc.mail2': '✉️ Email',
  'ctc.msg' : 'Messengers',
  'ctc.msg.note': 'On a phone, just tap the button. On a computer, tap the QR code to enlarge it and scan it with your phone.',
  'ctc.kakao'       : 'KakaoTalk',
  'ctc.kakao.qr'    : 'KakaoTalk QR code',
  'ctc.kakao.aria'  : 'Enlarge the KakaoTalk QR code',
  'ctc.kakao.go'    : 'Open the group chat',
  'ctc.kakao.copied': 'KakaoTalk ID copied. In KakaoTalk, go to Add friend → Add by ID and paste it.',
  'ctc.copy.id'     : 'Copy ID',
  'ctc.wa.qr'       : 'WhatsApp QR code',
  'ctc.wa.aria'     : 'Enlarge the WhatsApp QR code',
  'ctc.wa.go'       : 'Open a WhatsApp chat',
  'ctc.wa.copied'   : 'WhatsApp number copied.',
  'ctc.copy.num'    : 'Copy number',
  'ctc.wc'          : 'WeChat',
  'ctc.wc.qr'       : 'WeChat QR code',
  'ctc.wc.aria'     : 'Enlarge the WeChat QR code',
  'ctc.wc.copied'   : 'WeChat ID copied. In WeChat, go to Add contacts and paste it into the search box.',
  'ctc.copy.id2'    : 'Copy ID',
  'ctc.wc.save'     : 'Save QR image',
  'ctc.qr.title'    : 'QR code',
  'ctc.qr.note'     : 'Scan it with your phone camera or messenger app.',
  'ui.close'        : 'Close',

  /* ===== 하단 · 고정 바 ===== */
  'footer.mypage': 'Check my application →',
  'footer.addr'  : 'INFINITY Program · INFINITY Training Center, Kuala Lumpur, Malaysia',
  'bar.apply'    : '📝 Free consult',
  'bar.chat'     : '💬 WhatsApp',
  'bar.chat.href': 'https://wa.me/qr/HMQUC5RYMIVKO1',

  /* ===== 내 신청 확인 화면 (mypage.html) ===== */
  'my.meta.title' : 'My application | INFINITY Program',
  'my.logoAlt'    : 'INFINITY Program home',
  'my.home'       : '← Home',
  'my.h2'         : 'My application',
  'my.lead'       : 'Enter the <b>email</b> and the <b>last 4 digits of the phone number</b> you used when applying.<br>You can see your progress and your advisor’s reply, and ask further questions.',
  'my.email'      : 'Email',
  'my.phone4'     : 'Last 4 digits of your phone number',
  'my.phone4.ph'  : 'e.g. 5678',
  'my.phone4.hint': 'For +60 11-5392-<b>1378</b>, enter 1378',
  'my.lookup'     : 'Look up',
  'my.lock'       : '🔒 To protect your data, lookups are locked for <b>30 minutes after 5 failed attempts</b>.',
  'my.none'       : 'Never applied before? <a href="index.html#apply">Request a free consultation</a>',
  'my.title'      : 'My applications',
  'my.logout'     : 'Use different details',
  'my.mask'       : '🔒 Personal details are partly hidden with <b>*</b>. This screen expires after 30 minutes.',
  'my.urgent'     : 'For anything urgent, WhatsApp is fastest. <a href="https://wa.me/qr/HMQUC5RYMIVKO1" target="_blank" rel="noopener">Open a WhatsApp chat</a>',
  'my.backHome'   : '← Back to INFINITY Program home',

  /* ===== 버튼을 눌러야 나타나는 글자 (자바스크립트) ===== */
  'ui.copied'    : 'Copied.',
  'ui.copiedBtn' : '✓ Copied',
  'ui.copyFail'  : 'Copying is not supported here. Please type it in yourself: {text}',
  'ui.saveHint'  : 'Press and hold the QR image, then choose "Save to Photos".',

  'msg.name.empty' : 'Please enter your name.',
  'msg.name.short' : 'Please enter at least 2 characters.',
  'msg.name.digit' : 'Your name cannot contain numbers.',
  'msg.phone.empty': 'Please enter your phone number.',
  'msg.phone.intl' : 'Please enter your number starting with the country code. (e.g. +60 11-1234-5678)',
  'msg.phone.kr'   : 'Please enter a valid phone number. (e.g. 010-1234-5678, or +60 11-1234-5678)',
  'msg.email.empty': 'Please enter your email.',
  'msg.email.space': 'Your email contains a space.',
  'msg.email.form' : 'That email address does not look right. (e.g. example@gmail.com)',
  'msg.agree'      : 'You need to agree to the use of your personal data before applying.',
  'msg.emailTypo'  : 'Did you mean {addr}? ',
  'msg.emailFix'   : 'Use this instead',
  'msg.badFields'  : 'Please check the {n} field(s) marked in red.',
  'msg.sending'    : 'Sending…',
  'msg.ok'         : '✅ Your request has been received. An advisor will contact you shortly.',
  'msg.okId'       : 'Reference no. {id}',
  'msg.okMail'     : ' · We have sent a confirmation email to the address you entered.',
  'msg.mypage'     : 'Check my application →',
  'msg.fail'       : 'Something went wrong while sending. Please try again shortly, or contact us on WhatsApp.',
  'msg.direct'     : 'direct visit',

  'fd.need1'  : '👆 Please answer Q1 as well.',
  'fd.need2'  : '👇 Please answer Q2 as well.',
  'fd.badge'  : '🎯 Recommended programme',
  'fd.total'  : 'Total',
  'fd.apply'  : '📝 Request a consultation for this programme',
  'fd.detail' : 'See the full price',
  'fd.extra1' : '🎓 Want a UK university qualification too?',
  'fd.extra2' : 'See E. Birmingham Diploma (12 months, internship included) →',
  'fd.reset'  : '↺ Start over',
  'fd.a.title' : 'A. Cruise interview',
  'fd.a.price' : 'KRW 1,000,000<em class="fx">≈ US$721</em>',
  'fd.a.reason': 'You have both the English and the hotel experience! You can go straight to the cruise interview.',
  'fd.b.title' : 'B. Internship (6 months) + cruise interview',
  'fd.b.price' : 'KRW 5,200,000<em class="fx">≈ US$3,749</em>',
  'fd.b.reason': 'Your English is ready, so a paid 5-star hotel internship gives you the year of experience you need before the interview.',
  'fd.c.title' : 'C. English course (12 weeks) + cruise interview',
  'fd.c.price' : 'KRW 5,250,000<em class="fx">≈ US$3,785</em>',
  'fd.c.reason': 'You have plenty of hotel experience, so 12 weeks of English is all you need to be interview-ready.',
  'fd.d.title' : 'D. English course (12 weeks) + internship (6 months) + cruise interview',
  'fd.d.price' : 'KRW 9,600,000<em class="fx">≈ US$6,921</em>',
  'fd.d.reason': 'No problem at all — this is the route most people starting from scratch take. It covers both your English and your experience.',

  'my.email.bad'  : 'Please enter a valid email address.',
  'my.phone4.bad' : 'Please enter the last 4 digits of your phone number.',
  'my.checking'   : 'Checking…',
  'my.lookupFail' : 'There was a connection problem. Please try again shortly, or contact us on WhatsApp.',
  'my.titleN'     : 'My applications ({n})',
  'my.new'        : 'Received · not yet reviewed',
  'my.applied'    : 'Applied {date}',
  'my.f.name'     : 'Name',
  'my.f.phone'    : 'Phone',
  'my.f.email'    : 'Email',
  'my.f.program'  : 'Programme of interest',
  'my.f.english'  : 'English level',
  'my.f.langs'    : 'Other languages',
  'my.reply'      : '💬 Advisor reply',
  'my.reply.none' : 'No reply yet. An advisor will get in touch or leave a reply here.',
  'my.q.mine'     : 'Questions I have sent',
  'my.q.label'    : 'Anything else you would like to ask?',
  'my.q.ph'       : 'e.g. Could I also leave in October?',
  'my.q.send'     : 'Send question',
  'my.q.sending'  : 'Sending…',
  'my.q.short'    : 'Please write at least 2 characters.',
  'my.q.ok'       : '✅ Your question has been sent. An advisor will reply soon.',
  'my.q.fail'     : 'Something went wrong while sending. Please try again shortly.'
};
