/* =========================================================
   중국어(간체) 번역 사전 (12단계)

   - 왼쪽 "번호표"는 index.html / mypage.html 의 data-i18n="..." 과 똑같아야 합니다.
   - 오른쪽 글만 고치면 중국어 화면이 바뀝니다. HTML 은 건드리지 않아도 됩니다.
   - 중국에서는 카카오톡을 쓰지 않으므로, 상담 버튼은 위챗(연락처 칸)으로 보냅니다.
   - 금액은 원화 그대로 적었습니다 (예: 960万韩元). 환율이 바뀌면 곤란해서 위안화로 바꾸지 않았습니다.
   ========================================================= */
window.INFINITY_TEXT = window.INFINITY_TEXT || {};
window.INFINITY_TEXT.zh = {

  /* ===== 브라우저 탭 제목 · 검색 결과 설명 ===== */
  'meta.title': 'INFINITY Program | 国际邮轮乘务员就业',
  'meta.desc' : '大学毕业却找不到出路？一年后，你的工作地点可以是加勒比海上的六星级邮轮。INFINITY Program 免费咨询，现在申请。',

  /* ===== 상단 바 ===== */
  'header.logoAlt': 'INFINITY Program 标志',
  'header.cta'    : '免费咨询',

  /* ===== 1. 첫 화면 ===== */
  'hero.bgAlt' : '航行在海上的邮轮',
  'hero.trust' : '🏛️ 马来西亚政府认可的培训机构 · 毕业生 1,000 人以上',
  'hero.kicker': '大学毕业后，就业的大门却迟迟不开？',
  'hero.h1'    : '一年后，你的工作地点<br>是<em><span class="nowrap">加勒比海上的</span> <span class="nowrap">六星级酒店</span></em>',
  'hero.sub'   : '一边环游世界，一边赚取美元薪资。<br>食宿全部免费，薪水可以<strong>全额存下来</strong>。',
  'hero.b1': '以美元（USD）<br>发放薪资',
  'hero.b2': '薪资免征所得税<small>依据公海工作规定</small>',
  'hero.b3': '食宿<br>全部免费',
  'hero.b4': '拿着薪水<br>环游世界',
  'hero.btnApply'    : '📝 申请免费咨询',
  'hero.btnChat'     : '💬 微信 1:1 在线咨询',
  'hero.btnChat.href': '#contact',

  /* ===== 2. 현실 비교 ===== */
  'cmp.h2'  : '同样的一年，<br>你想在哪里度过？',
  'cmp.lead': '今天的选择，决定一年后你站在什么位置。',
  'cmp.them': '在国内找工作',
  'cmp.us'  : '国际邮轮乘务员',
  'cmp.r1' : '📅 一年后的样子',
  'cmp.r1a': '<span class="sr-only">在国内找工作：</span>还在积累履历、投递简历',
  'cmp.r1b': '<span class="sr-only">国际邮轮乘务员：</span>在六星级酒店级别的邮轮上工作',
  'cmp.r2' : '💵 薪资',
  'cmp.r2a': '<span class="sr-only">在国内找工作：</span>本国货币，还要扣税',
  'cmp.r2b': '<span class="sr-only">国际邮轮乘务员：</span>美元（USD），薪资免征所得税',
  'cmp.r3' : '🏠 生活费',
  'cmp.r3a': '<span class="sr-only">在国内找工作：</span>房租、伙食、交通都要自己负担',
  'cmp.r3b': '<span class="sr-only">国际邮轮乘务员：</span>食宿全部免费提供',
  'cmp.r4' : '🐷 存款',
  'cmp.r4a': '<span class="sr-only">在国内找工作：</span>扣掉生活费后所剩无几',
  'cmp.r4b': '<span class="sr-only">国际邮轮乘务员：</span>薪水大部分都能存下来',
  'cmp.r5' : '✈️ 经历',
  'cmp.r5a': '<span class="sr-only">在国内找工作：</span>只有国内工作经历',
  'cmp.r5b': '<span class="sr-only">国际邮轮乘务员：</span>环游世界 + 海外工作经历（应聘酒店、航空公司更有优势）',
  'cmp.punch': '同样的一年，<b>存款和简历</b>却完全不同。',
  'cmp.cta'  : '我也可以吗？先免费咨询看看',

  /* ===== 3. 무료 상담 신청서 ===== */
  'form.h2'  : '申请免费咨询及入学资料',
  'form.lead': '留下申请表，负责人会直接与您联系。',
  'form.name'       : '姓名',
  'form.name.ph'    : '例）张伟',
  'form.phone'      : '联系电话',
  'form.phone.ph'   : '+86 138-1234-5678',
  'form.phone.hint' : '请从国家区号开始填写，例如 +86 或 +60',
  'form.email'      : '电子邮箱',
  'form.eng'        : '目前英语口语水平（选填）',
  'form.choose'     : '请选择',
  'form.eng1'       : '入门（能简单打招呼）',
  'form.eng2'       : '初级（能进行简单对话）',
  'form.eng3'       : '中级（能进行日常对话）',
  'form.eng4'       : '高级（能进行工作对话）',
  'form.langs'      : '会说的其他语言（选填）',
  'form.langs.ph'   : '例）韩语－中级。没有的话请填“无”',
  'form.prog'       : '感兴趣的项目（选填）',
  'form.choose2'    : '请选择',
  'form.prog.a'     : '邮轮面试',
  'form.prog.b'     : '实习（6个月）+ 邮轮面试',
  'form.prog.c'     : '英语课程（12周）+ 邮轮面试',
  'form.prog.d'     : '英语课程（12周）+ 实习（6个月）+ 邮轮面试',
  'form.prog.e'     : '伯明翰 Diploma（12个月）',
  'form.prog.x'     : '还不确定',
  'form.agree'      : '我同意收集和使用本人的个人信息',
  'form.agree.more' : '查看详细内容',
  'form.pp1'        : '收集项目：姓名、联系电话、电子邮箱、英语水平、会说的语言、感兴趣的项目',
  'form.pp2'        : '使用目的：就业咨询及入学资料说明',
  'form.pp3'        : '保存期限：咨询结束后 1 年（如提出要求可立即删除）',
  'form.pp4'        : '您可以不同意，但这种情况下将无法受理咨询申请。',
  'form.submit'     : '申请免费咨询及入学资料',
  'form.foot'       : '※ 您填写的信息仅用于就业咨询，不作他用。',

  /* ===== 4. 국제 크루즈란? ===== */
  'cr.h2'  : '国际邮轮乘务员，待遇就是不一样',
  'cr.img1': '航行在大海上的邮轮',
  'cr.p1': '<strong>视同六星级酒店工作经历</strong> — 日后应聘酒店、航空公司更有优势',
  'cr.p2': '<strong>以美元（USD）发放薪资</strong> — 薪资免税（依据公海工作规定）',
  'cr.p3': '<strong>晋升快，加薪机会多</strong>',
  'cr.p4': '<strong>生活所需一应俱全</strong> — 住宿、餐饮等船上全部提供',
  'cr.stats': '用数字看 INFINITY',
  'cr.s1': '<b>1,000人+</b>毕业生',
  'cr.s2': '<b>35家+</b>国际邮轮官方合作公司',
  'cr.s3': '<b>KL</b>位于马来西亚吉隆坡的邮轮专业培训中心',
  'cr.s4': '合作公司所在地区：美国、阿拉斯加、挪威、地中海、东南亚',
  'cr.gov': '<b>马来西亚政府认可的正规教育机构</b>可自行签发学生签证 · 普通语言学校无法办理',
  'cr.img2': '国际邮轮合作公司',
  'cr.img2.cap': '35 家以上邮轮公司可就业',
  'cr.job'      : '具体做什么工作？',
  'cr.job.lead' : '根据英语水平和面试表现，在 <strong>16 个部门、76 个职位</strong> 中进行分配。（不同职位薪资有差异）',
  'cr.d1': '客房管理',
  'cr.d2': '船上厨房',
  'cr.d3': '酒店',
  'cr.d4': '饮品服务',
  'cr.d5': '餐饮',
  'cr.d6': '甲板',
  'cr.d7': '烹饪',
  'cr.d8': '轮机',
  'cr.d9': '餐厅',
  'cr.d10': '娱乐场',
  'cr.d11': '讲师',
  'cr.d12': '管理岗',
  'cr.d13': '招聘',
  'cr.d14': '客房服务',
  'cr.d15': '技术',
  'cr.d16': '其他',
  'cr.d.note': '部门名称旁边的数字是该部门的职位数量。',
  'cr.d.more': '示例：查看客房管理（HOUSEKEEPING）部门的 12 个职位',
  'cr.img3': '邮轮大小对比',
  'cr.req' : '申请条件',
  'cr.req1': '年满 21 岁、未满 35 岁',
  'cr.req2': '高中及以上学历',
  'cr.req3': '能用英语进行口语交流',
  'cr.req4': '五星级酒店或旅游相关工作经验 1 年以上',
  'cr.req.note': '条件不足也没关系。英语不够可以先读<strong>英语课程</strong>，没有经验可以通过<strong>五星级酒店实习</strong>来补足。',

  /* ===== 5. 나에게 맞는 프로그램 찾기 ===== */
  'fd.h2'   : '找到适合我的项目',
  'fd.lead' : '回答两个问题，就能得到合适的项目推荐。',
  'fd.q1'   : 'Q1. 能用英语进行日常对话吗？',
  'fd.yes1' : '是',
  'fd.no1'  : '否',
  'fd.q2'   : 'Q2. 有 1 年以上酒店或旅游相关工作经验吗？',
  'fd.yes2' : '是',
  'fd.no2'  : '否',
  'fd.empty': '回答完两个问题后，就会出现推荐结果。',

  /* ===== 6. 프로그램 A~D ===== */
  'fx.note': '※ 人民币金额按 2026 年 9 月 20 日汇率换算（1 元 = 206 韩元），会随汇率变动。实际价格以韩元金额为准。',
  'pg.h2': '项目介绍',
  'pg.a.t'  : 'A. 邮轮面试',
  'pg.a.who': '适合英语口语和酒店经验<strong>两者都具备</strong>的人',
  'pg.b.t'  : 'B. 实习（6个月）+ 邮轮面试',
  'pg.b.who': '适合英语没问题，但<strong>没有酒店经验</strong>的人',
  'pg.c.t'  : 'C. 英语课程（12周）+ 邮轮面试',
  'pg.c.who': '适合有酒店经验，但<strong>英语不够好</strong>的人',
  'pg.d.t'  : 'D. 英语课程（12周）+ 实习（6个月）+ 邮轮面试',
  'pg.d.who': '适合英语和经验<strong>两者都需要</strong>的人',
  'pg.i.visa'  : '旅游签证',
  'pg.i.intv'  : '邮轮面试（初试 / 复试 / 终面）',
  'pg.i.intv2' : '邮轮面试（初试 / 复试 / 终面）',
  'pg.i.pick'  : '机场接机',
  'pg.i.svisa' : '1 年学生签证（含当地体检费）<a href="#gov-certified" class="gov-tag">政府认可机构签发</a>',
  'pg.i.intern': '五星级酒店实习安排（6个月）',
  'pg.i.eng'   : 'INFINITY 12 周语言课程（含注册费、分级测试）',
  'pg.v.0'   : '免费',
  'pg.v.10'  : '10万韩元<em class="fx">≈ 485元</em>',
  'pg.v.75'  : '75万韩元<em class="fx">≈ 3,641元</em>',
  'pg.v.100' : '100万韩元<em class="fx">≈ 4,854元</em>',
  'pg.v.135' : '135万韩元<em class="fx">≈ 6,553元</em>',
  'pg.v.300' : '300万韩元<em class="fx">≈ 14,563元</em>',
  'pg.v.440' : '440万韩元<em class="fx">≈ 21,359元</em>',
  'pg.total' : '合计', 'pg.v.100b': '100万韩元<em class="fx">≈ 4,854元</em>',
  'pg.total2': '合计', 'pg.v.520' : '520万韩元<em class="fx">≈ 25,243元</em>',
  'pg.total3': '合计', 'pg.v.525' : '525万韩元<em class="fx">≈ 25,485元</em>',
  'pg.total4': '合计', 'pg.v.960' : '960万韩元<em class="fx">≈ 46,602元</em>',
  'pg.total5': '合计',
  'pg.ex' : '所有项目共同的不含项目',
  'pg.ex1': '机票、住宿费、当地交通费、个人零用钱',
  'pg.ex2': '通过面试后的登船准备代办费（约 72万韩元 / 3,495元，各邮轮公司不同）',
  'pg.ex3': '回国后登船准备所需的签证及材料费用（约 60万韩元 / 2,913元）',
  'pg.ex4': '住宿请参考下方的 <a href="#housing">住宿介绍</a>。',

  /* ===== 7. 버밍엄 Diploma ===== */
  'bcu.badge': 'SPECIAL · 英国大学 Diploma',
  'bcu.logo' : '伯明翰城市大学标志',
  'bcu.h2'   : 'E. 英国伯明翰城市大学 Diploma（12个月）',
  'bcu.lead' : '在英国需要 2 年 6 个月的大专（Diploma）课程，在马来西亚 INFINITY <strong>含实习仅需 12 个月</strong>即可毕业。毕业后可直接衔接国际邮轮终面。',
  'bcu.p1': '颁发英国伯明翰城市大学 Diploma 毕业证书',
  'bcu.p2': '升读其他大学时可获学分认可',
  'bcu.p3': '可在英国大学官方网站查询毕业生信息',
  'bcu.img1': 'Diploma 毕业证书实物照片',
  'bcu.img2': '英国大学网站毕业生查询页面',
  'ui.swipe': '左右滑动查看 →',
  'bcu.major': '三个专业',
  'bcu.m1': 'Diploma in Hospitality Operations（酒店运营）',
  'bcu.m2': 'Diploma in Food Preparation & Culinary Arts（烹饪）',
  'bcu.m3': 'Diploma in Food & Beverage Service Operations（餐饮服务）',
  'bcu.img3' : '各专业科目构成',
  'bcu.intake': '招生时间：<strong>每年 1 月、4 月、7 月、10 月</strong>',
  'bcu.req' : '申请条件',
  'bcu.req1': '年满 19 岁、未满 35 岁',
  'bcu.req2': '高中及以上学历',
  'bcu.req3': '具备初级英语口语能力',
  'bcu.req4': '无出境限制',
  'bcu.tl' : '流程（以 4 月申请为例）',
  'bcu.tl1': '<strong>2026 年 4 月</strong> — 项目咨询及申请',
  'bcu.tl2': '<strong>2026 年 5 月</strong> — 办理学生签证（约 4 周），入境马来西亚，开始英语课程（6个月）',
  'bcu.tl3': '<strong>2026 年 11 月</strong> — 开始五星级酒店实习（6个月），结业后颁发 Diploma 毕业证书',
  'bcu.tl4': '<strong>2027 年 5 月</strong> — 国际邮轮面试',
  'bcu.tl5': '<strong>2027 年 6 月</strong> — 回国，STCW 培训及材料准备，等待美国签证批准（最长 4 周）',
  'bcu.tl6': '<strong>2027 年 7 月</strong> — 前往录取邮轮公司的出发港，开始工作',
  'bcu.img4': '抵达马来西亚机场',
  'bcu.img5': '新生说明会',
  'bcu.img6': '参加伯明翰项目的学生',
  'bcu.price': '价格',
  'bcu.pr1': '<a href="#gov-certified" class="gov-tag">政府认可机构签发</a>签证及入学手续（机场接机、1 年学生签证、当地体检、签证印花费、手续管理）',
  'bcu.pr2': 'Diploma 课程（24周）+ 五星级酒店实习（6个月）',
  'bcu.pr3': '邮轮面试（初试 / 复试 / 终面）',
  'bcu.v'  : '1,370万韩元<em class="fx">≈ 66,505元</em>',
  'bcu.pr.note': '不含项目与 A~D 项目相同。',
  'bcu.vs'   : '两年制大专 vs 伯明翰项目',
  'bcu.vs.h1': '', 'bcu.vs.h2': '本国两年制大专', 'bcu.vs.h3': '伯明翰项目',
  'bcu.vs.a1': '学制',   'bcu.vs.a2': '2 年', 'bcu.vs.a3': '12 个月（含实习）',
  'bcu.vs.b1': '学费',   'bcu.vs.b2': '2,000万韩元以上<em class="fx">≈ 97,087元 · 每学期平均约 500万韩元（24,272元）</em>', 'bcu.vs.b3': '1,370万韩元<em class="fx">≈ 66,505元</em>',
  'bcu.vs.c1': '学历',   'bcu.vs.c2': '本国大专文凭', 'bcu.vs.c3': '英国伯明翰城市大学 Diploma',
  'bcu.vs.d1': '就业衔接', 'bcu.vs.d2': '无', 'bcu.vs.d3': '含国际邮轮初试·复试·终面',

  /* ===== 8. 교육센터 ===== */
  'ct.h2'  : 'INFINITY 培训中心',
  'ct.lead': '经马来西亚教育部（M.O.E）正式认证的培训中心，位于吉隆坡市中心。同时是 IELTS 官方合作伙伴及国际邮轮乘务员中介机构。',
  'ct.gov.h': '马来西亚政府认可的<br>正规教育机构',
  'ct.gov.p': '<b>并不是任何学校都能签发学生签证。</b><br>只有马来西亚政府认可的教育机构才可以。',
  'ct.gov.no'  : '普通语言学校',
  'ct.gov.no1' : '没有政府正式认证',
  'ct.gov.no2' : '<b>根本无法签发学生签证</b>',
  'ct.gov.yes' : 'INFINITY 培训中心',
  'ct.gov.yes1': '马来西亚教育部（M.O.E）正式认证',
  'ct.gov.yes2': '<b>可自行签发学生签证</b>',
  'ct.gov.foot': '因此在 INFINITY，凭<b>1 年学生签证</b>就能安心完成英语课程并衔接五星级酒店实习。',
  'ct.t1': '具备国际学校授课经验的专业师资',
  'ct.t2': '从初级到高级的分级英语课程（含成人班）',
  'ct.t3': '1:1 授课及 3~5 人小班授课',
  'ct.img1': '培训中心入口',
  'ct.img2': '上课情景',
  'ct.img3': '上课情景',
  'ct.img4': '培训中心的学生们',
  'ct.fac': '设施',
  'ct.f1': '1:1 教室 11 间',
  'ct.f2': '1:8 教室 8 间',
  'ct.f3': '1:25 教室 1 间',
  'ct.f4': '1:50 演讲厅 1 间',
  'ct.f5': '休息室',
  'ct.img5': '1:1 教室',
  'ct.img6': '演讲厅',
  'ct.img7': '休息室',
  'ct.img8': '培训中心位置地图',
  'ct.img8.cap': '步行 5 分钟',
  'ct.in' : '五星级酒店带薪实习（6个月）',
  'ct.in1': '与当地经理面谈后，按照经验和意向领域进行分配',
  'ct.in2': '月薪约 RM1,200',
  'ct.in3': '结业后颁发五星级酒店工作结业证书（申请邮轮时提交，可认定为 1 年工作经历）',
  'ct.img9' : '实习酒店',
  'ct.img10': '实习酒店',
  'ct.img11': '在实习酒店工作的情景',

  /* ===== 9. 합격 과정 ===== */
  'pc.h2': '通往录取的流程',
  'pc.s1' : '<strong>视频咨询</strong> — 报名前与 INFINITY 邮轮负责人面谈（经验不足时，可用 6 个月酒店实习提高录取率）',
  'pc.s2' : '邮轮面试',
  'pc.s2b': ' — 在课程期间进行',
  'pc.s2c': '性格测评（电脑作答，各邮轮公司不同）',
  'pc.s2d': '英语测试（电脑作答，各公司相同，通过后 1 年内有效）',
  'pc.s2e': '终面（英语面试）',
  'pc.s3' : '<strong>录取</strong> — 同时取得美国乘务员工作签证（C1/D）和美国 10 年旅游签证（B1/B2）',
  'pc.s4' : '<strong>未通过时</strong> — 配合下一次面试时间准备重考',
  'pc.img1': '视频面试',
  'pc.img2': '终面',
  'pc.img3': '最终录取通知书',
  'pc.img4': '邮轮乘务员',
  'pc.prep': '录取后需在本国准备的事项',
  'pc.th1': '项目', 'pc.th2': '内容', 'pc.th3': '所需时间', 'pc.th4': '费用',
  'pc.t1a': '健康体检', 'pc.t1b': '指定医院体检（血液、胸部 X 光等）', 'pc.t1c': '约 1 个月', 'pc.t1d': '约 20~35万韩元<em class="fx">≈ 971~1,699元</em>',
  'pc.t2a': '材料准备', 'pc.t2b': '无犯罪记录证明（警察局）、海员手册（地方海洋水产厅）', 'pc.t2c': '1 天', 'pc.t2d': '约 1万韩元<em class="fx">≈ 49元</em>',
  'pc.t3a': '美国签证', 'pc.t3b': '凭录取通知书申请 C1/D、B1/B2 签证', 'pc.t3c': '约 10 天', 'pc.t3d': '约 20万韩元<em class="fx">≈ 971元</em>',
  'pc.t4b': '海上安全培训（嘉年华邮轮为登船后自行培训）', 'pc.t4c': '约 1 个半月', 'pc.t4d': '约 18万韩元<em class="fx">≈ 874元</em>',
  'pc.note': '※ 所需材料可能因邮轮公司而异，录取后我们会详细说明。',

  /* ===== 10. 숙소 ===== */
  'hs.h2'  : '住宿介绍',
  'hs.note': '※ 以下住宿为<strong>示例</strong>。视当地情况，可能会调整为水准相当的其他公寓。',
  'hs.a' : 'A 型：Vipod Residences',
  'hs.a1': '大房间 RM2,500 / 月',
  'hs.a2': '小房间 RM2,000 / 月',
  'hs.a3': '步行 5 分钟到培训中心',
  'hs.a4': '含 WiFi，电费另计',
  'hs.ia1': 'A 型卧室', 'hs.ia2': 'A 型客厅', 'hs.ia3': 'A 型厨房', 'hs.ia4': 'A 型泳池',
  'hs.b' : 'B 型：One-Stop Residences（两种房型）',
  'hs.b1': '双人间 RM1,000 / 每人',
  'hs.b2': '单人间 RM2,000 / 每人',
  'hs.b3': '距培训中心地铁 2 站',
  'hs.b4': '含 WiFi，电费另计，可使用健身房',
  'hs.ib1': 'B 型卧室', 'hs.ib2': 'B 型客厅', 'hs.ib3': 'B 型厨房', 'hs.ib4': 'B 型泳池', 'hs.ib5': 'B 型健身房',

  /* ===== 11. 연락처 ===== */
  'ctc.h2'  : '欢迎随时联系我们',
  'ctc.tel' : '电话',
  'ctc.kr'  : '🇰🇷 韩国',
  'ctc.my'  : '🇲🇾 马来西亚',
  'ctc.mail': '电子邮箱',
  'ctc.mail2': '✉️ 电子邮箱',
  'ctc.msg' : '即时通讯',
  'ctc.msg.note': '用手机浏览时请直接点击按钮；用电脑浏览时请点击二维码放大，再用手机扫描。',
  'ctc.kakao'       : 'KakaoTalk',
  'ctc.kakao.qr'    : 'KakaoTalk 二维码',
  'ctc.kakao.aria'  : '放大查看 KakaoTalk 二维码',
  'ctc.kakao.go'    : '进入开放聊天室',
  'ctc.kakao.copied': '已复制 KakaoTalk ID。请在 KakaoTalk 中进入“添加好友 → 按 ID 添加”并粘贴。',
  'ctc.copy.id'     : '复制 ID',
  'ctc.wa.qr'       : 'WhatsApp 二维码',
  'ctc.wa.aria'     : '放大查看 WhatsApp 二维码',
  'ctc.wa.go'       : '打开 WhatsApp 对话',
  'ctc.wa.copied'   : '已复制 WhatsApp 号码。',
  'ctc.copy.num'    : '复制号码',
  'ctc.wc'          : '微信 (WeChat)',
  'ctc.wc.qr'       : '微信二维码',
  'ctc.wc.aria'     : '放大查看微信二维码',
  'ctc.wc.copied'   : '已复制微信 ID。请在微信中进入“添加朋友”，粘贴到搜索框。',
  'ctc.copy.id2'    : '复制 ID',
  'ctc.wc.save'     : '保存二维码图片',
  'ctc.qr.title'    : '二维码',
  'ctc.qr.note'     : '请用手机相机或聊天软件扫描。',
  'ui.close'        : '关闭',

  /* ===== 하단 · 고정 바 ===== */
  'footer.mypage': '查看我的申请 →',
  'footer.addr'  : 'INFINITY Program · INFINITY Training Center, Kuala Lumpur, Malaysia',
  'bar.apply'    : '📝 免费咨询',
  'bar.chat'     : '💬 微信咨询',
  'bar.chat.href': '#contact',

  /* ===== 내 신청 확인 화면 (mypage.html) ===== */
  'my.meta.title' : '查看我的申请 | INFINITY Program',
  'my.logoAlt'    : '返回 INFINITY Program 首页',
  'my.home'       : '← 首页',
  'my.h2'         : '查看我的申请',
  'my.lead'       : '请输入申请咨询时填写的<b>电子邮箱</b>和<b>电话号码后 4 位</b>。<br>您可以查看办理进度和负责人的回复，也可以继续提问。',
  'my.email'      : '电子邮箱',
  'my.phone4'     : '电话号码后 4 位',
  'my.phone4.ph'  : '例）5678',
  'my.phone4.hint': '如果是 +60 11-5392-<b>1378</b>，就填 1378',
  'my.lookup'     : '查询',
  'my.lock'       : '🔒 为保护个人信息，<b>连续输错 5 次将锁定 30 分钟</b>。',
  'my.none'       : '还没有申请过吗？<a href="index.html#apply">申请免费咨询</a>',
  'my.title'      : '我的申请记录',
  'my.logout'     : '用其他信息查询',
  'my.mask'       : '🔒 个人信息会用 <b>*</b> 部分遮挡显示。此页面 30 分钟后需要重新验证。',
  'my.urgent'     : '紧急咨询用微信最快。<a href="#contact">查看微信二维码</a>',
  'my.backHome'   : '← 返回 INFINITY Program 首页',

  /* ===== 버튼을 눌러야 나타나는 글자 (자바스크립트) ===== */
  'ui.copied'    : '已复制。',
  'ui.copiedBtn' : '✓ 已复制',
  'ui.copyFail'  : '当前环境无法复制，请手动输入：{text}',
  'ui.saveHint'  : '请长按二维码图片，选择“保存到相册”。',

  'msg.name.empty' : '请输入姓名。',
  'msg.name.short' : '姓名请输入 2 个字以上。',
  'msg.name.digit' : '姓名中不能包含数字。',
  'msg.phone.empty': '请输入联系电话。',
  'msg.phone.intl' : '请从国家区号开始正确填写号码。（例：+86 138-1234-5678）',
  'msg.phone.kr'   : '请正确填写电话号码。（例：+86 138-1234-5678）',
  'msg.email.empty': '请输入电子邮箱。',
  'msg.email.space': '电子邮箱中含有空格。',
  'msg.email.form' : '电子邮箱格式不正确。（例：example@gmail.com）',
  'msg.agree'      : '需要同意收集和使用个人信息后才能提交申请。',
  'msg.emailTypo'  : '您是想填 {addr} 吗？ ',
  'msg.emailFix'   : '改成这个',
  'msg.badFields'  : '请检查标红的 {n} 个项目。',
  'msg.sending'    : '发送中…',
  'msg.ok'         : '✅ 申请已受理。负责人会尽快与您联系。',
  'msg.okId'       : '申请编号 {id}',
  'msg.okMail'     : ' · 我们已向您填写的邮箱发送了受理确认邮件。',
  'msg.mypage'     : '查看我的申请 →',
  'msg.fail'       : '发送过程中出现问题。请稍后重试，或通过微信联系我们。',
  'msg.direct'     : '直接访问',

  'fd.need1'  : '👆 请也回答 Q1。',
  'fd.need2'  : '👇 请也回答 Q2。',
  'fd.badge'  : '🎯 推荐项目',
  'fd.total'  : '合计',
  'fd.apply'  : '📝 用这个项目申请咨询',
  'fd.detail' : '查看详细价格',
  'fd.extra1' : '🎓 想同时拿到英国大学文凭吗？',
  'fd.extra2' : '查看 E. 伯明翰 Diploma（12个月，含实习）→',
  'fd.reset'  : '↺ 重新开始',
  'fd.a.title' : 'A. 邮轮面试',
  'fd.a.price' : '100万韩元<em class="fx">≈ 4,854元</em>',
  'fd.a.reason': '英语口语和酒店经验您都具备！可以直接挑战邮轮面试。',
  'fd.b.title' : 'B. 实习（6个月）+ 邮轮面试',
  'fd.b.price' : '520万韩元<em class="fx">≈ 25,243元</em>',
  'fd.b.reason': '英语已经没问题，通过五星级酒店带薪实习取得 1 年工作经历后再去面试即可。',
  'fd.c.title' : 'C. 英语课程（12周）+ 邮轮面试',
  'fd.c.price' : '525万韩元<em class="fx">≈ 25,485元</em>',
  'fd.c.reason': '酒店经验已经足够，只要用 12 周英语课程准备好面试英语就可以了。',
  'fd.d.title' : 'D. 英语课程（12周）+ 实习（6个月）+ 邮轮面试',
  'fd.d.price' : '960万韩元<em class="fx">≈ 46,602元</em>',
  'fd.d.reason': '完全没问题。这是零基础起步的人最常选择的路线，英语和经验一次补足。',

  'my.email.bad'  : '请正确填写电子邮箱地址。',
  'my.phone4.bad' : '请输入电话号码后 4 位数字。',
  'my.checking'   : '确认中…',
  'my.lookupFail' : '连接出现问题。请稍后重试，或通过微信联系我们。',
  'my.titleN'     : '我的申请记录（{n} 条）',
  'my.new'        : '已受理 · 负责人尚未确认',
  'my.applied'    : '{date} 申请',
  'my.f.name'     : '姓名',
  'my.f.phone'    : '联系电话',
  'my.f.email'    : '电子邮箱',
  'my.f.program'  : '感兴趣的项目',
  'my.f.english'  : '英语水平',
  'my.f.langs'    : '会说的语言',
  'my.reply'      : '💬 负责人回复',
  'my.reply.none' : '目前还没有回复。负责人确认后会与您联系，或在这里留下回复。',
  'my.q.mine'     : '我发送的追加提问',
  'my.q.label'    : '还有其他想了解的吗？',
  'my.q.ph'       : '例）10 月出发也可以吗？',
  'my.q.send'     : '发送提问',
  'my.q.sending'  : '发送中…',
  'my.q.short'    : '提问内容请输入 2 个字以上。',
  'my.q.ok'       : '✅ 提问已发送。负责人确认后会回复您。',
  'my.q.fail'     : '发送过程中出现问题。请稍后重试。'
};
